name: Java CI with Maven v2.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker Image
      run: docker build -t loancalculator:test .
    - name: Test Docker Image
      run: docker run --rm loancalculator:test | grep 'successfully'
  
  movie-info:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checking out the action
        uses: actions/checkout@v2
        with:
          repository: the-iron-bank-of-volantis/tib-movie-info-private
          ref: v1.0
          token: ${{secrets.REPOSITORY_ACTION_ACCESS_TOKEN}}
          pah: ./.github/actions/tib-movie-info-private-action
      - name: the-iron-bank-got-movie-info
        # You may pin to the exact commit or the version.
        # uses: the-iron-bank-of-volantis/tib-movie-info@76575532143c07a2f7267d18ac52ca45227da4be
        uses: ./.github/actions/tib-movie-info-private-action
        with:
          # Open Movie Database api-key to retrieve the information
          api-key: ${{secrets.API_TOKEN}}
